# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_auto_20171128_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(),
        ),
    ]
