# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_auto_20171128_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
