# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0013_recipe_ingred_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_types',
            field=models.CharField(default='', max_length=100),
        ),
    ]
