# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0016_auto_20171129_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='natural_occ',
            field=models.TextField(default=''),
        ),
    ]
