# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0017_compound_natural_occ'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
