# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0018_ingredient_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmi',
            name='co_occ',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pmi',
            name='cond_prob',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pmi',
            name='pmi',
            field=models.FloatField(default=0),
        ),
    ]
