# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0019_auto_20171129_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essence',
            name='ingre_type',
            field=models.CharField(choices=[('M', 'Meat'), ('V', 'Vegetable'), ('F', 'Fruit'), ('SE', 'Seafood'), ('D', 'Dairy'), ('N', 'Nuts'), ('G', 'Grains'), ('SP', 'Spice'), ('A', 'Alcohol'), ('O', 'Other')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='assoc_recipes', to='recommendation.Ingredient'),
        ),
    ]
