# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20171127_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='aisle',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingre_type',
            field=models.CharField(default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='compound',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Aisle',
        ),
    ]
