# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_auto_20171127_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
