# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20171127_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingre_type',
        ),
        migrations.AddField(
            model_name='essence',
            name='ingre_type',
            field=models.CharField(default='OTHER', max_length=20),
        ),
    ]
