# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_auto_20171127_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='spoonacularID',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
