# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0011_auto_20171128_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instruction',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
