# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0012_auto_20171128_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingred_list',
            field=models.CharField(default='', max_length=100),
        ),
    ]
