# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0015_auto_20171128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essence',
            name='ingre_type',
            field=models.CharField(choices=[('SE', 'Seafood'), ('F', 'Fruit'), ('V', 'Vegetable'), ('SP', 'Spice'), ('M', 'Meat'), ('O', 'Other'), ('D', 'Dairy'), ('N', 'Nuts'), ('G', 'Grains'), ('A', 'Alcohol')], default='O', max_length=20),
        ),
    ]
